### ISSUE TITLE
Server does not start on Windows

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-adapters#150]
Tried on Windows and noticed the server is started but exit quickly.
Adding some listeners while starting the process produced:

```
C:\Users\JeffMAURY\AppData\Local\Programs\Microsoft VS Code\Code.exe --debugBrkPluginHost=16933 --debugId=5c2bc559-9aa5-4780-9c72-5aae6873667b --extensionDevelopmentPath=C:\work\vscode-adapters 
stderr:sept. 20, 2018 1:55:21 PM org.jline.utils.Log logr

AVERTISSEMENT: Error in WindowsStreamPump

java.io.IOException: ReadConsoleInputW failed

	at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:816)

	at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:99)

	at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:75)

	at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:455)

	at java.lang.Thread.run(Thread.java:748)



java.lang.NullPointerException

	at org.jline.terminal.impl.AbstractWindowsTerminal.close(AbstractWindowsTerminal.java:216)

	at org.apache.felix.gogo.jline.Activator.lambda$startShell$1(Activator.java:159)

	at org.apache.felix.gogo.jline.Activator.stopShell(Activator.java:182)

	at org.apache.felix.gogo.jline.Activator.serviceLost(Activator.java:81)

	at org.apache.felix.gogo.jline.SingleServiceTracker.update(SingleServiceTracker.java:169)

	at org.apache.felix.gogo.jline.SingleServiceTracker.findMatchingReference(SingleServiceTracker.java:133)

	at org.apache.felix.gogo.jline.SingleServiceTracker.serviceChanged(SingleServiceTracker.java:102)

	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)

	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)

	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)

	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4827)

	at org.apache.felix.framework.Felix.access$000(Felix.java:110)

	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:430)

	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:170)

	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:145)

	at org.apache.felix.gogo.runtime.activator.Activator.stop(Activator.java:128)

	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:719)

	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2791)

	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1553)

	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)

	at java.lang.Thread.run(Thread.java:748)


stdout:Minishift Server bundle started

Wildfly Server bundle started

The server management server is running on port 27511

ERROR: Bundle org.apache.felix.gogo.jline [5] EventDispatcher: Error during dispatch. (java.lang.NullPointerException)



```

**Comment by jeffmaury** [comment]
This issue was moved to redhat-developer/rsp-server#46
