### ISSUE TITLE
If java not found extension should suggest to download and install openjdk from developers.redhat.com

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-adapters#173]
It just fails right now without any clue how to solve the problem:
![java-not-found](https://user-images.githubusercontent.com/620330/47699357-d7cc3e00-dbcf-11e8-9fbe-3f77e820c1e1.png)
``` shell
Activating extension `redhat.vscode-adapters` failed:  not found: javac
extensionHostProcess.js:293
Here is the error stack:  Error: not found: javac
extensionHostProcess.js:293
	at F (/home/eskimo/Projects/vscode-adapters/node_modules/which/which.js:40:28)
	at E (/home/eskimo/Projects/vscode-adapters/node_modules/which/which.js:43:29)
	at /home/eskimo/Projects/vscode-adapters/node_modules/which/which.js:54:16
	at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by adietish** [comment]
this is duplicate to #220 where the fix was to present an error dialog which allows users to open up the download page for java.
